### ISSUE TITLE
Redirection by Soundcloud results in unusable filename

### ISSUE THREAD

**Issue by CentristOuevre** [chessgriffin/mashpodder#10]
Hello. Is this project still maintained?

When an enclosure URL gets redirected, the header information that we end up with spits out a non-MP3 string to FILENAME, like AeJSWj43K3QA. 

I know it can be solved by having cURL or wget use Content-Disposition to get the correct header info, but I can't get my head around it.

Here's an example.

I tried running the line `DLURL=$($CURL -s -I -L -w %{url_effective} --url $URL | tail -n 1)`, which I think is the source of the redirected header information, like so:

`curl -s -I -L -w %{url_effective} --url http://feeds.soundcloud.com/stream/199963631-with-special-guest-lauren-lapkus-casey-feigh-dave-theune-nba-on-npr.mp3 | tail -n 1`

I get this output:

`http://cf-media.sndcdn.com/AeJSWj43K3QA?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vQWVKU1dqNDNLM1FBIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDI4OTM1NDM0fX19XX0_&Signature=hWP8c1v7bhezjRY80w27r5kX1ONiL3DBAvtW65buO1WiZE26m10iXS293O7UPsXgEmQeYL281WqmtOwZ44hdeHRhplhLitRok8HNwart2g8c9kUbisgl6K-2QDnO04ok52buVt5jTQXDqgYh-Nw19QranYEorHWZtAHdlkKjeDJHE0lilND1xIx--8f61YP6ldX6yarh991qIDeahpMh6QLZvN2uF6XELi7a8hxAASwpQDY0sSNKtjlj32cvray8AEedHRceiQV2iWHZG4pTVGOUC6p~si3xChR75FKTnSJfVDMKYaxqGpuck3eyeY95KtyUx8lKh-udEifmV4nPAw__&Key-Pair-Id=APKAJAGZ7VMH2PFPW6UQ`

and this is the resulting filename when mashpodder is actually run:

`AeJSWj43K3QA`

**Comment by rickyhobby** [comment]
(I'm not maintaining this, FWIW)

If your issue is that the resultant filename is not optimal, and that the file "AeJSWj43K3QA" is a/the mp3 file, and your problem is just file naming, you could try changing line 402 of the current version of chessgriffin/mashpodder mashpodder.sh from:

fix_url $DLURL
to
fix_url $URL

which sets the filename to the name listed in the feed rather than the name of the redirected file.


I also have encountered this issue and I have in my fork a commit that works around this problem.

https://github.com/rickyhobby/mashpodder/commit/3f43a24b990fa83c7cad93f12c7a26fd5a947813

My commit reads the basename of the file in the feed's enclosure tag, and uses it as the resultant basename of the filename, and then reads the redirected extension and uses that as the resultant extension in the filename.  This may not work for you as your redirected filename does not have an extension.  I am unsure of how my version will handle the fact that the redirected file has no extension.  Specifically, I don't know how bash handles ${FILENAME##*.} (the bash command to extract the extension) when there is no extension.  Most likely either give an error or set the variable to null.  Which in either case, for your usage, is not ideal.  Why my version is not simply the line 402 change is that in my case, the feed I was having issues with I wanted the feed's filename and the redirected extension.  

While I don't have time right now, I will at some point investigate this and make my code work like it does now, and test for the absence of an extension, and use the feed's extension if absent.

Take care,
Rick

**Comment by CentristOuevre** [comment]
Thanks for the fork. I also found the $DLURL/$URL change worked for me.

**Comment by chessgriffin** [comment]
Thanks - I am no longer maintaining mashpodder so thanks for posting the issue and the fix.
